#!/bin/bash
exec < /dev/tty && node_modules/.bin/cz --hook || true

echo '🏗️👷 Styling your project before committing👷🏗️'
echo 'please be patient, this may take a while...'

pnpm lint ||
(
    echo '🔨❌ Yoo, you have a problem in your code. Check linter 🔨❌
          Run pnpm lint, add changes and try commit again.';
    false;
)
 
echo '🎉 No error found: committing this now.... ✨🚀🏄‍♂️🍻'
 
pnpm lint-staged